backend:
  name: github
  repo: topiahq/website #replace with your username/repo

media_folder: static/assets

collections:
  - name: banner
    label: banner
    folder: "markdowns_files/banner"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: heading, label: heading, widget: markdown }
      - { name: slug, label: slug, widget: hidden, default: banner }

  - name: areas
    label: areas
    folder: "markdowns_files/areas"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: slug, label: slug, widget: hidden, default: Area }
      - { name: heading, label: heading, widget: string }
      - { name: description, label: Area description, widget: markdown }
      - { name: image, label: Area icon, widget: image }
      - { label: "soon", name: "soon", widget: "boolean", default: false }

  - name: Area main title
    label: Area main title
    folder: "markdowns_files/area_title"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: name, label: description, widget: markdown }
      - { name: slug, label: slug, widget: hidden, default: mianTitle }

  - name: team
    label: team
    folder: "markdowns_files/teams"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: name, label: name, widget: string }
      - { name: info, label: description, widget: markdown }
      - { name: image, label: member photo, widget: image }
      - { name: doodle, label: doodle photo, widget: image }
      - { name: slug, label: slug, widget: hidden, default: team }

  - name: mail
    label: mail
    folder: "markdowns_files/mail"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: info, label: description, widget: markdown }
      - { name: slug, label: slug, widget: hidden, default: mail }
