backend:
  name: github
  repo: muhammadqamar/Topia #replace with your username/repo

media_folder: static/assets

collections:
  - name: banner
    label: banner
    folder: "markdowns_files/banner"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: heading, label: heading, widget: markdown }
      - { name: slug-banner, label: slug-banner, widget: "hidden" }

  - name: areas
    label: areas
    folder: "markdowns_files/areas"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: slug-areas, label: slug-areas, widget: "hidden" }
      - { name: heading, label: heading, widget: string }
      - { name: description, label: Area description, widget: markdown }

      - { name: image, label: Area icon, widget: image }

  - name: team
    label: team
    folder: "markdowns_files/teams"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: name, label: name, widget: string }
      - { name: info, label: description, widget: markdown }
      - { name: image, label: member photo, widget: image }
      - { name: doodle, label: doodle photo, widget: image }
      - { name: slug-team, label: slug-team, widget: "hidden" }
